apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-cluster
  name: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-cluster
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-cluster
    spec:
      containers:
        - env:
            - name: ADV_HOST
              value: 127.0.0.1
            - name: RUNTESTS
              value: "0"
          image: landoop/fast-data-dev:cp3.3.0
          name: kafka-cluster
          ports:
            - containerPort: 2181
            - containerPort: 3030
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 8083
            - containerPort: 9581
            - containerPort: 9582
            - containerPort: 9583
            - containerPort: 9584
            - containerPort: 9585
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
status: {}
